# Generated by Django 4.1.2 on 2022-11-01 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_colaborador_departamento_colaborador_entidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='usuario',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
