# Generated by Django 4.1.1 on 2022-09-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('razon_social', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('name', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('rut', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
