# Generated by Django 4.1.1 on 2022-09-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rut',
        ),
    ]
