# Generated by Django 4.1.1 on 2022-09-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_profile_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
