# Generated by Django 4.1.1 on 2022-09-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='profile',
        ),
    ]
