# Generated by Django 4.1.1 on 2022-09-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_documento_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
