# Generated by Django 4.1.2 on 2022-10-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
